// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: obs_sync.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DataStream
type DataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sign string `protobuf:"bytes,1,opt,name=sign,proto3" json:"sign,omitempty"`
}

func (x *DataRequest) Reset() {
	*x = DataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_obs_sync_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataRequest) ProtoMessage() {}

func (x *DataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_obs_sync_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataRequest.ProtoReflect.Descriptor instead.
func (*DataRequest) Descriptor() ([]byte, []int) {
	return file_obs_sync_proto_rawDescGZIP(), []int{0}
}

func (x *DataRequest) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

type UriInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type         string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Scheme       string `protobuf:"bytes,2,opt,name=scheme,proto3" json:"scheme,omitempty"`
	BucketDomain string `protobuf:"bytes,3,opt,name=BucketDomain,proto3" json:"BucketDomain,omitempty"`
	AccessKey    string `protobuf:"bytes,4,opt,name=accessKey,proto3" json:"accessKey,omitempty"`
	SecretKey    string `protobuf:"bytes,5,opt,name=secretKey,proto3" json:"secretKey,omitempty"`
}

func (x *UriInfo) Reset() {
	*x = UriInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_obs_sync_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UriInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UriInfo) ProtoMessage() {}

func (x *UriInfo) ProtoReflect() protoreflect.Message {
	mi := &file_obs_sync_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UriInfo.ProtoReflect.Descriptor instead.
func (*UriInfo) Descriptor() ([]byte, []int) {
	return file_obs_sync_proto_rawDescGZIP(), []int{1}
}

func (x *UriInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UriInfo) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *UriInfo) GetBucketDomain() string {
	if x != nil {
		return x.BucketDomain
	}
	return ""
}

func (x *UriInfo) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *UriInfo) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

type Object struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Size  int64  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Mtime int64  `protobuf:"varint,3,opt,name=mtime,proto3" json:"mtime,omitempty"`
	IsDir bool   `protobuf:"varint,4,opt,name=isDir,proto3" json:"isDir,omitempty"`
}

func (x *Object) Reset() {
	*x = Object{}
	if protoimpl.UnsafeEnabled {
		mi := &file_obs_sync_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Object) ProtoMessage() {}

func (x *Object) ProtoReflect() protoreflect.Message {
	mi := &file_obs_sync_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Object.ProtoReflect.Descriptor instead.
func (*Object) Descriptor() ([]byte, []int) {
	return file_obs_sync_proto_rawDescGZIP(), []int{2}
}

func (x *Object) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Object) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Object) GetMtime() int64 {
	if x != nil {
		return x.Mtime
	}
	return 0
}

func (x *Object) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

type TaskInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BucketName string    `protobuf:"bytes,1,opt,name=bucketName,proto3" json:"bucketName,omitempty"`
	SrcUri     *UriInfo  `protobuf:"bytes,2,opt,name=srcUri,proto3" json:"srcUri,omitempty"`
	DestUri    *UriInfo  `protobuf:"bytes,3,opt,name=destUri,proto3" json:"destUri,omitempty"`
	Objects    []*Object `protobuf:"bytes,4,rep,name=objects,proto3" json:"objects,omitempty"`
}

func (x *TaskInfo) Reset() {
	*x = TaskInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_obs_sync_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInfo) ProtoMessage() {}

func (x *TaskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_obs_sync_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInfo.ProtoReflect.Descriptor instead.
func (*TaskInfo) Descriptor() ([]byte, []int) {
	return file_obs_sync_proto_rawDescGZIP(), []int{3}
}

func (x *TaskInfo) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *TaskInfo) GetSrcUri() *UriInfo {
	if x != nil {
		return x.SrcUri
	}
	return nil
}

func (x *TaskInfo) GetDestUri() *UriInfo {
	if x != nil {
		return x.DestUri
	}
	return nil
}

func (x *TaskInfo) GetObjects() []*Object {
	if x != nil {
		return x.Objects
	}
	return nil
}

type DataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Task *TaskInfo `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
}

func (x *DataResponse) Reset() {
	*x = DataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_obs_sync_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataResponse) ProtoMessage() {}

func (x *DataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_obs_sync_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataResponse.ProtoReflect.Descriptor instead.
func (*DataResponse) Descriptor() ([]byte, []int) {
	return file_obs_sync_proto_rawDescGZIP(), []int{4}
}

func (x *DataResponse) GetTask() *TaskInfo {
	if x != nil {
		return x.Task
	}
	return nil
}

// PutResult
type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BucketName string   `protobuf:"bytes,1,opt,name=bucketName,proto3" json:"bucketName,omitempty"`
	WorkIP     string   `protobuf:"bytes,2,opt,name=workIP,proto3" json:"workIP,omitempty"`
	Success    []string `protobuf:"bytes,3,rep,name=success,proto3" json:"success,omitempty"`
	Failed     []string `protobuf:"bytes,4,rep,name=failed,proto3" json:"failed,omitempty"`
	DeadlSize  int64    `protobuf:"varint,5,opt,name=deadlSize,proto3" json:"deadlSize,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_obs_sync_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_obs_sync_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_obs_sync_proto_rawDescGZIP(), []int{5}
}

func (x *Result) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *Result) GetWorkIP() string {
	if x != nil {
		return x.WorkIP
	}
	return ""
}

func (x *Result) GetSuccess() []string {
	if x != nil {
		return x.Success
	}
	return nil
}

func (x *Result) GetFailed() []string {
	if x != nil {
		return x.Failed
	}
	return nil
}

func (x *Result) GetDeadlSize() int64 {
	if x != nil {
		return x.DeadlSize
	}
	return 0
}

type Replay struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *Replay) Reset() {
	*x = Replay{}
	if protoimpl.UnsafeEnabled {
		mi := &file_obs_sync_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Replay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Replay) ProtoMessage() {}

func (x *Replay) ProtoReflect() protoreflect.Message {
	mi := &file_obs_sync_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Replay.ProtoReflect.Descriptor instead.
func (*Replay) Descriptor() ([]byte, []int) {
	return file_obs_sync_proto_rawDescGZIP(), []int{6}
}

func (x *Replay) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

//HasMore
type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_obs_sync_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_obs_sync_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_obs_sync_proto_rawDescGZIP(), []int{7}
}

type HasMoreReplay struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Has bool `protobuf:"varint,1,opt,name=has,proto3" json:"has,omitempty"`
}

func (x *HasMoreReplay) Reset() {
	*x = HasMoreReplay{}
	if protoimpl.UnsafeEnabled {
		mi := &file_obs_sync_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HasMoreReplay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasMoreReplay) ProtoMessage() {}

func (x *HasMoreReplay) ProtoReflect() protoreflect.Message {
	mi := &file_obs_sync_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasMoreReplay.ProtoReflect.Descriptor instead.
func (*HasMoreReplay) Descriptor() ([]byte, []int) {
	return file_obs_sync_proto_rawDescGZIP(), []int{8}
}

func (x *HasMoreReplay) GetHas() bool {
	if x != nil {
		return x.Has
	}
	return false
}

//Sync
type Auth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Region    string `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	AccessKey string `protobuf:"bytes,3,opt,name=accessKey,proto3" json:"accessKey,omitempty"`
	SecretKey string `protobuf:"bytes,4,opt,name=secretKey,proto3" json:"secretKey,omitempty"`
}

func (x *Auth) Reset() {
	*x = Auth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_obs_sync_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth) ProtoMessage() {}

func (x *Auth) ProtoReflect() protoreflect.Message {
	mi := &file_obs_sync_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth.ProtoReflect.Descriptor instead.
func (*Auth) Descriptor() ([]byte, []int) {
	return file_obs_sync_proto_rawDescGZIP(), []int{9}
}

func (x *Auth) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Auth) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Auth) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *Auth) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

type SyncInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Src  *Auth `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	Dest *Auth `protobuf:"bytes,2,opt,name=dest,proto3" json:"dest,omitempty"`
}

func (x *SyncInfo) Reset() {
	*x = SyncInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_obs_sync_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncInfo) ProtoMessage() {}

func (x *SyncInfo) ProtoReflect() protoreflect.Message {
	mi := &file_obs_sync_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncInfo.ProtoReflect.Descriptor instead.
func (*SyncInfo) Descriptor() ([]byte, []int) {
	return file_obs_sync_proto_rawDescGZIP(), []int{10}
}

func (x *SyncInfo) GetSrc() *Auth {
	if x != nil {
		return x.Src
	}
	return nil
}

func (x *SyncInfo) GetDest() *Auth {
	if x != nil {
		return x.Dest
	}
	return nil
}

type SyncReplay struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  string            `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Buckets []*SyncReplay_Row `protobuf:"bytes,2,rep,name=Buckets,proto3" json:"Buckets,omitempty"`
}

func (x *SyncReplay) Reset() {
	*x = SyncReplay{}
	if protoimpl.UnsafeEnabled {
		mi := &file_obs_sync_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncReplay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncReplay) ProtoMessage() {}

func (x *SyncReplay) ProtoReflect() protoreflect.Message {
	mi := &file_obs_sync_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncReplay.ProtoReflect.Descriptor instead.
func (*SyncReplay) Descriptor() ([]byte, []int) {
	return file_obs_sync_proto_rawDescGZIP(), []int{11}
}

func (x *SyncReplay) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SyncReplay) GetBuckets() []*SyncReplay_Row {
	if x != nil {
		return x.Buckets
	}
	return nil
}

//
type Value struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scanned    int64 `protobuf:"varint,1,opt,name=Scanned,proto3" json:"Scanned,omitempty"`
	Skipped    int64 `protobuf:"varint,2,opt,name=Skipped,proto3" json:"Skipped,omitempty"`
	Copied     int64 `protobuf:"varint,3,opt,name=Copied,proto3" json:"Copied,omitempty"`
	Failed     int64 `protobuf:"varint,4,opt,name=Failed,proto3" json:"Failed,omitempty"`
	Size       int64 `protobuf:"varint,5,opt,name=Size,proto3" json:"Size,omitempty"`
	FinishFlag bool  `protobuf:"varint,6,opt,name=FinishFlag,proto3" json:"FinishFlag,omitempty"`
}

func (x *Value) Reset() {
	*x = Value{}
	if protoimpl.UnsafeEnabled {
		mi := &file_obs_sync_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_obs_sync_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_obs_sync_proto_rawDescGZIP(), []int{12}
}

func (x *Value) GetScanned() int64 {
	if x != nil {
		return x.Scanned
	}
	return 0
}

func (x *Value) GetSkipped() int64 {
	if x != nil {
		return x.Skipped
	}
	return 0
}

func (x *Value) GetCopied() int64 {
	if x != nil {
		return x.Copied
	}
	return 0
}

func (x *Value) GetFailed() int64 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *Value) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Value) GetFinishFlag() bool {
	if x != nil {
		return x.FinishFlag
	}
	return false
}

type Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *Value `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Status) Reset() {
	*x = Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_obs_sync_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_obs_sync_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_obs_sync_proto_rawDescGZIP(), []int{13}
}

func (x *Status) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type StopResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskName string `protobuf:"bytes,1,opt,name=TaskName,proto3" json:"TaskName,omitempty"`
	Status   string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *StopResult) Reset() {
	*x = StopResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_obs_sync_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResult) ProtoMessage() {}

func (x *StopResult) ProtoReflect() protoreflect.Message {
	mi := &file_obs_sync_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResult.ProtoReflect.Descriptor instead.
func (*StopResult) Descriptor() ([]byte, []int) {
	return file_obs_sync_proto_rawDescGZIP(), []int{14}
}

func (x *StopResult) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *StopResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type TaskStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bucket  string `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Status  string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Summary string `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
}

func (x *TaskStatus) Reset() {
	*x = TaskStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_obs_sync_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatus) ProtoMessage() {}

func (x *TaskStatus) ProtoReflect() protoreflect.Message {
	mi := &file_obs_sync_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatus.ProtoReflect.Descriptor instead.
func (*TaskStatus) Descriptor() ([]byte, []int) {
	return file_obs_sync_proto_rawDescGZIP(), []int{15}
}

func (x *TaskStatus) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *TaskStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskStatus) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type StatReplay struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskStatus []*TaskStatus `protobuf:"bytes,1,rep,name=taskStatus,proto3" json:"taskStatus,omitempty"`
}

func (x *StatReplay) Reset() {
	*x = StatReplay{}
	if protoimpl.UnsafeEnabled {
		mi := &file_obs_sync_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatReplay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatReplay) ProtoMessage() {}

func (x *StatReplay) ProtoReflect() protoreflect.Message {
	mi := &file_obs_sync_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatReplay.ProtoReflect.Descriptor instead.
func (*StatReplay) Descriptor() ([]byte, []int) {
	return file_obs_sync_proto_rawDescGZIP(), []int{16}
}

func (x *StatReplay) GetTaskStatus() []*TaskStatus {
	if x != nil {
		return x.TaskStatus
	}
	return nil
}

type BucketSummary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Scan    int64  `protobuf:"varint,2,opt,name=scan,proto3" json:"scan,omitempty"`
	Success int64  `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Fail    int64  `protobuf:"varint,4,opt,name=fail,proto3" json:"fail,omitempty"`
	Finish  bool   `protobuf:"varint,5,opt,name=finish,proto3" json:"finish,omitempty"`
}

func (x *BucketSummary) Reset() {
	*x = BucketSummary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_obs_sync_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BucketSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketSummary) ProtoMessage() {}

func (x *BucketSummary) ProtoReflect() protoreflect.Message {
	mi := &file_obs_sync_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketSummary.ProtoReflect.Descriptor instead.
func (*BucketSummary) Descriptor() ([]byte, []int) {
	return file_obs_sync_proto_rawDescGZIP(), []int{17}
}

func (x *BucketSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BucketSummary) GetScan() int64 {
	if x != nil {
		return x.Scan
	}
	return 0
}

func (x *BucketSummary) GetSuccess() int64 {
	if x != nil {
		return x.Success
	}
	return 0
}

func (x *BucketSummary) GetFail() int64 {
	if x != nil {
		return x.Fail
	}
	return 0
}

func (x *BucketSummary) GetFinish() bool {
	if x != nil {
		return x.Finish
	}
	return false
}

type StatResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value         *Value           `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	BucketSummary []*BucketSummary `protobuf:"bytes,2,rep,name=bucketSummary,proto3" json:"bucketSummary,omitempty"`
}

func (x *StatResult) Reset() {
	*x = StatResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_obs_sync_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResult) ProtoMessage() {}

func (x *StatResult) ProtoReflect() protoreflect.Message {
	mi := &file_obs_sync_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResult.ProtoReflect.Descriptor instead.
func (*StatResult) Descriptor() ([]byte, []int) {
	return file_obs_sync_proto_rawDescGZIP(), []int{18}
}

func (x *StatResult) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *StatResult) GetBucketSummary() []*BucketSummary {
	if x != nil {
		return x.BucketSummary
	}
	return nil
}

type SyncReplay_Row struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cells []string `protobuf:"bytes,1,rep,name=cells,proto3" json:"cells,omitempty"`
}

func (x *SyncReplay_Row) Reset() {
	*x = SyncReplay_Row{}
	if protoimpl.UnsafeEnabled {
		mi := &file_obs_sync_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncReplay_Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncReplay_Row) ProtoMessage() {}

func (x *SyncReplay_Row) ProtoReflect() protoreflect.Message {
	mi := &file_obs_sync_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncReplay_Row.ProtoReflect.Descriptor instead.
func (*SyncReplay_Row) Descriptor() ([]byte, []int) {
	return file_obs_sync_proto_rawDescGZIP(), []int{11, 0}
}

func (x *SyncReplay_Row) GetCells() []string {
	if x != nil {
		return x.Cells
	}
	return nil
}

var File_obs_sync_proto protoreflect.FileDescriptor

var file_obs_sync_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6f, 0x62, 0x73, 0x5f, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x73, 0x79, 0x6e, 0x63, 0x22, 0x21, 0x0a, 0x0b, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x22, 0x95, 0x01, 0x0a, 0x07, 0x55, 0x72,
	0x69, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x63, 0x68,
	0x65, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d,
	0x65, 0x12, 0x22, 0x0a, 0x0c, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x44, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x44,
	0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4b,
	0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x4b, 0x65, 0x79,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x4b, 0x65,
	0x79, 0x22, 0x5a, 0x0a, 0x06, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x6d, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x73, 0x44, 0x69, 0x72,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x69, 0x73, 0x44, 0x69, 0x72, 0x22, 0xa2, 0x01,
	0x0a, 0x08, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x75,
	0x63, 0x6b, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x06, 0x73, 0x72,
	0x63, 0x55, 0x72, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x73, 0x79, 0x6e,
	0x63, 0x2e, 0x55, 0x72, 0x69, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x73, 0x72, 0x63, 0x55, 0x72,
	0x69, 0x12, 0x27, 0x0a, 0x07, 0x64, 0x65, 0x73, 0x74, 0x55, 0x72, 0x69, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x55, 0x72, 0x69, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x07, 0x64, 0x65, 0x73, 0x74, 0x55, 0x72, 0x69, 0x12, 0x26, 0x0a, 0x07, 0x6f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x73, 0x79,
	0x6e, 0x63, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x73, 0x22, 0x32, 0x0a, 0x0c, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x22, 0x90, 0x01, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x50, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x50, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x06, 0x66, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x64,
	0x65, 0x61, 0x64, 0x6c, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x64, 0x65, 0x61, 0x64, 0x6c, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x20, 0x0a, 0x06, 0x52, 0x65, 0x70,
	0x6c, 0x61, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x07, 0x0a, 0x05, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x22, 0x21, 0x0a, 0x0d, 0x48, 0x61, 0x73, 0x4d, 0x6f, 0x72, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x61, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x68, 0x61, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x03, 0x68, 0x61, 0x73, 0x22, 0x6e, 0x0a, 0x04, 0x41, 0x75, 0x74, 0x68, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x61,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x4b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65,
	0x63, 0x72, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x22, 0x48, 0x0a, 0x08, 0x53, 0x79, 0x6e, 0x63, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x0a, 0x03, 0x73, 0x72, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x52, 0x03, 0x73, 0x72,
	0x63, 0x12, 0x1e, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x52, 0x04, 0x64, 0x65, 0x73,
	0x74, 0x22, 0x71, 0x0a, 0x0a, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x79, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2e, 0x0a, 0x07, 0x42, 0x75, 0x63, 0x6b, 0x65,
	0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x79, 0x6e, 0x63, 0x2e,
	0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x79, 0x2e, 0x52, 0x6f, 0x77, 0x52, 0x07,
	0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x1a, 0x1b, 0x0a, 0x03, 0x52, 0x6f, 0x77, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x65, 0x6c, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x63,
	0x65, 0x6c, 0x6c, 0x73, 0x22, 0x9f, 0x01, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x53, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x53, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x6b, 0x69, 0x70,
	0x70, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x53, 0x6b, 0x69, 0x70, 0x70,
	0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x6f, 0x70, 0x69, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x43, 0x6f, 0x70, 0x69, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x46, 0x61,
	0x69, 0x6c, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x46, 0x61, 0x69, 0x6c,
	0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68,
	0x46, 0x6c, 0x61, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x46, 0x69, 0x6e, 0x69,
	0x73, 0x68, 0x46, 0x6c, 0x61, 0x67, 0x22, 0x2b, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x21, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x40, 0x0a, 0x0a, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x61, 0x73, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x54, 0x61, 0x73, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x56, 0x0a, 0x0a, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x22, 0x3e, 0x0a,
	0x0a, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x79, 0x12, 0x30, 0x0a, 0x0a, 0x74,
	0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x0a, 0x74, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x7d, 0x0a,
	0x0d, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x63, 0x61, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x73, 0x63, 0x61, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x66, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x66, 0x61, 0x69, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x22, 0x6a, 0x0a, 0x0a,
	0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x21, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x73, 0x79, 0x6e, 0x63,
	0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x39, 0x0a,
	0x0d, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x42, 0x75, 0x63, 0x6b,
	0x65, 0x74, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x0d, 0x62, 0x75, 0x63, 0x6b, 0x65,
	0x74, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x32, 0xc3, 0x02, 0x0a, 0x04, 0x50, 0x69, 0x70,
	0x65, 0x12, 0x39, 0x0a, 0x0a, 0x44, 0x61, 0x74, 0x61, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12,
	0x11, 0x2e, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x12, 0x2e, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x29, 0x0a, 0x09,
	0x50, 0x75, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0c, 0x2e, 0x73, 0x79, 0x6e, 0x63,
	0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x1a, 0x0c, 0x2e, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x52,
	0x65, 0x70, 0x6c, 0x61, 0x79, 0x22, 0x00, 0x12, 0x2d, 0x0a, 0x07, 0x48, 0x61, 0x73, 0x4d, 0x6f,
	0x72, 0x65, 0x12, 0x0b, 0x2e, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x13, 0x2e, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x48, 0x61, 0x73, 0x4d, 0x6f, 0x72, 0x65, 0x52, 0x65,
	0x70, 0x6c, 0x61, 0x79, 0x22, 0x00, 0x12, 0x2a, 0x0a, 0x04, 0x53, 0x79, 0x6e, 0x63, 0x12, 0x0e,
	0x2e, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x10,
	0x2e, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x79,
	0x22, 0x00, 0x12, 0x26, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x0b, 0x2e, 0x73, 0x79,
	0x6e, 0x63, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0c, 0x2e, 0x73, 0x79, 0x6e, 0x63, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x30, 0x01, 0x12, 0x27, 0x0a, 0x04, 0x53, 0x74,
	0x6f, 0x70, 0x12, 0x0b, 0x2e, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x10, 0x2e, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x22, 0x00, 0x12, 0x29, 0x0a, 0x04, 0x53, 0x74, 0x61, 0x74, 0x12, 0x0b, 0x2e, 0x73, 0x79,
	0x6e, 0x63, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x10, 0x2e, 0x73, 0x79, 0x6e, 0x63, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x30, 0x01, 0x42, 0x09,
	0x5a, 0x07, 0x73, 0x79, 0x6e, 0x63, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_obs_sync_proto_rawDescOnce sync.Once
	file_obs_sync_proto_rawDescData = file_obs_sync_proto_rawDesc
)

func file_obs_sync_proto_rawDescGZIP() []byte {
	file_obs_sync_proto_rawDescOnce.Do(func() {
		file_obs_sync_proto_rawDescData = protoimpl.X.CompressGZIP(file_obs_sync_proto_rawDescData)
	})
	return file_obs_sync_proto_rawDescData
}

var file_obs_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_obs_sync_proto_goTypes = []interface{}{
	(*DataRequest)(nil),    // 0: sync.DataRequest
	(*UriInfo)(nil),        // 1: sync.UriInfo
	(*Object)(nil),         // 2: sync.Object
	(*TaskInfo)(nil),       // 3: sync.TaskInfo
	(*DataResponse)(nil),   // 4: sync.DataResponse
	(*Result)(nil),         // 5: sync.Result
	(*Replay)(nil),         // 6: sync.Replay
	(*Empty)(nil),          // 7: sync.Empty
	(*HasMoreReplay)(nil),  // 8: sync.HasMoreReplay
	(*Auth)(nil),           // 9: sync.Auth
	(*SyncInfo)(nil),       // 10: sync.SyncInfo
	(*SyncReplay)(nil),     // 11: sync.SyncReplay
	(*Value)(nil),          // 12: sync.Value
	(*Status)(nil),         // 13: sync.Status
	(*StopResult)(nil),     // 14: sync.StopResult
	(*TaskStatus)(nil),     // 15: sync.TaskStatus
	(*StatReplay)(nil),     // 16: sync.StatReplay
	(*BucketSummary)(nil),  // 17: sync.BucketSummary
	(*StatResult)(nil),     // 18: sync.StatResult
	(*SyncReplay_Row)(nil), // 19: sync.SyncReplay.Row
}
var file_obs_sync_proto_depIdxs = []int32{
	1,  // 0: sync.TaskInfo.srcUri:type_name -> sync.UriInfo
	1,  // 1: sync.TaskInfo.destUri:type_name -> sync.UriInfo
	2,  // 2: sync.TaskInfo.objects:type_name -> sync.Object
	3,  // 3: sync.DataResponse.task:type_name -> sync.TaskInfo
	9,  // 4: sync.SyncInfo.src:type_name -> sync.Auth
	9,  // 5: sync.SyncInfo.dest:type_name -> sync.Auth
	19, // 6: sync.SyncReplay.Buckets:type_name -> sync.SyncReplay.Row
	12, // 7: sync.Status.value:type_name -> sync.Value
	15, // 8: sync.StatReplay.taskStatus:type_name -> sync.TaskStatus
	12, // 9: sync.StatResult.value:type_name -> sync.Value
	17, // 10: sync.StatResult.bucketSummary:type_name -> sync.BucketSummary
	0,  // 11: sync.Pipe.DataStream:input_type -> sync.DataRequest
	5,  // 12: sync.Pipe.PutResult:input_type -> sync.Result
	7,  // 13: sync.Pipe.HasMore:input_type -> sync.Empty
	10, // 14: sync.Pipe.Sync:input_type -> sync.SyncInfo
	7,  // 15: sync.Pipe.Start:input_type -> sync.Empty
	7,  // 16: sync.Pipe.Stop:input_type -> sync.Empty
	7,  // 17: sync.Pipe.Stat:input_type -> sync.Empty
	4,  // 18: sync.Pipe.DataStream:output_type -> sync.DataResponse
	6,  // 19: sync.Pipe.PutResult:output_type -> sync.Replay
	8,  // 20: sync.Pipe.HasMore:output_type -> sync.HasMoreReplay
	11, // 21: sync.Pipe.Sync:output_type -> sync.SyncReplay
	13, // 22: sync.Pipe.Start:output_type -> sync.Status
	14, // 23: sync.Pipe.Stop:output_type -> sync.StopResult
	18, // 24: sync.Pipe.Stat:output_type -> sync.StatResult
	18, // [18:25] is the sub-list for method output_type
	11, // [11:18] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_obs_sync_proto_init() }
func file_obs_sync_proto_init() {
	if File_obs_sync_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_obs_sync_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_obs_sync_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UriInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_obs_sync_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Object); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_obs_sync_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_obs_sync_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_obs_sync_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_obs_sync_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Replay); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_obs_sync_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_obs_sync_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HasMoreReplay); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_obs_sync_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Auth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_obs_sync_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_obs_sync_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncReplay); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_obs_sync_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Value); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_obs_sync_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_obs_sync_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_obs_sync_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_obs_sync_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatReplay); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_obs_sync_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BucketSummary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_obs_sync_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_obs_sync_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncReplay_Row); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_obs_sync_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_obs_sync_proto_goTypes,
		DependencyIndexes: file_obs_sync_proto_depIdxs,
		MessageInfos:      file_obs_sync_proto_msgTypes,
	}.Build()
	File_obs_sync_proto = out.File
	file_obs_sync_proto_rawDesc = nil
	file_obs_sync_proto_goTypes = nil
	file_obs_sync_proto_depIdxs = nil
}
